### ISSUE TITLE
Python code generation from .ui files should be automated

### ISSUE THREAD

**Issue by mrdaemon** [ccfreak2k/BESM-Character-Resolver#5]
The Designer forms (.ui) should be compiled by devs and the resulting python files should not be added under version control.
This increases the chance of a disparity between ui and actual code.

Relevant paths should be added to gitignore and a method of automating generation should be devised.

I will handle this as part of the project layout refactoring if no one minds.

**Comment by Knifa** [comment]
The .ui file is Qt Designer file, though, is it not? Surely we want this on file?

**Comment by mrdaemon** [comment]
Yes, that one is fine. I'd personally shove it in a completely external directory in the root level, and have a build script run pyuic4 on it to generate the .py files for the forms, and have these added in git ignore. That sounds like the sanest way to go at it to me :)

**Comment by ccfreak2k** [comment]
Well, syncing the ui file would be desirable simply because we're using that to design the GUI. It could be excluded in a -release- pack, but for development purposes we want it to make changes to the GUI windows. Anything generated -from- the ui file can be excluded, though, but the file itself is a source file nonetheless.

**Comment by mrdaemon** [comment]
That is what I meant from the start. Just keep the .ui (QtDesigner file), but ditch the generated python file and have devs generate it.
